version: "3.8"
services:
  webapp:
    build: .
    container_name: fra-monitor
    ports:
      - "3000:3000"
    environment:
      - MQTT_HOST=79d9b250811241cda17602225df019b9.s1.eu.hivemq.cloud
      - MQTT_PORT=8883
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - PORT=3000
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - fra-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    networks:
      - fra-network
    restart: unless-stopped

volumes:
  mosquitto-data:
  mosquitto-logs:

networks:
